book/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', MainPageView.as_view(), name='home'),
    path('book-detail/<int:pk>/', BookDetailView.as_view(), name='detail'),
    path('add-book/', BookCreateView.as_view(), name='add-book'),
    path('add-category/', add_category, name='add-category'),
    path('add-author/', add_author, name='add-author'),
    path('update-book/<int:pk>/', BookUpdateView.as_view(), name='update-book'),
    path('delete-book/<int:pk>/', BookDeleteView.as_view(), name='delete-book'),
    path(r'borrowed/', LoanedBooksAllListView.as_view(), name='all-borrowed'),
    path('borrow/', BorrowCreateView.as_view(), name='borrow'),
    path(r'borrowed/', LoanedBooksAllListView.as_view(), name='all-borrowed'),

]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('account/', include('account.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
import uuid
from django.db import models
from account.models import User
from datetime import date


class Category(models.Model):
    slug = models.SlugField(primary_key=True, max_length=50)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True, default='It is a new book')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    publish_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField()

    def __str__(self) -> str:
        return self.title


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    due_back = models.DateField(null=True, blank=True)
    date_borrow = models.DateField(auto_now_add=True)
    borrower = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    # def __str__(self):
    #     """String for representing the Model object."""
    #     return '{0} ({1})'.format(self.id, self.book.title)

    def __str__(self) -> str:
        return self.title

templates/add.html
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
     <input class="btn btn-primary" type="submit" value="Submit">
</form>

{% endblock %}

templates/add_authors.html
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ formset.management_form }}
    {% for form in formset %}
    {{ form }}
    {% endfor %}
     <input class="btn btn-primary" type="submit" value="Submit">
</form>

{% endblock %}

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html xmlns="http://www.w3.org/1999/html">
	<head>
        <title>{% block title %} {% endblock%}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">
						<div class="inner">

							<!-- Header -->
								<header id="header">
									<ul class="icons">
										{% if not request.user.is_authenticated %}
										<a href="{% url 'register' %}"><i class="fa fa-registered" aria-hidden="true"></i></a>
										<a href="{% url 'login' %}"><i class="far fa-user-circle"></i></a>
										{% else %}
										<a href="{% url 'logout' %}"><i class="fas fa-user-circle"></i></a>
										{% endif %}
									</ul>
								</header>
                            {% block content %} {% endblock %}
                               </div>
					</div>

                            <!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">

							<!-- Search -->
								<section id="search" class="alt">
									<form method="get" action="{% url 'home' %}">
										<input type="text" name="q" id="query" placeholder="Search" />
									</form>
								</section>

							<!-- Menu -->
								<nav id="menu">
									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="{% url 'home'%}">Homepage</a></li>
										{% if request.user.is_superuser %}
										<li><a href="{% url 'add-book' %}">Add new Book</a></li>
										<li><a href="{% url 'add-author' %}">Add new Author</a></li>
										<li><a href="{% url 'add-category' %}">Add new Category</a></li>
										<li><a href="{% url 'borrow' %}">Borrow</a></li>
										{% endif %}
										{% if request.user.is_authenticated %}
										<li><a href="{% url 'profile' %}?filter=new">Profile</a></li>
										<li><a href="{% url 'all-borrowed' %}">All Borrowed</a></li>


										{% endif %}
									</ul>
								</nav>


								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<p>Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
									<ul class="contact">
										<li class="icon solid fa-envelope"><a href="#">admin@admin.com</a></li>
										<li class="icon solid fa-phone">(000) 000-0000</li>
									</ul>
								</section>

						</div>
					</div>

			</div>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>
	</body>
</html>

templates/book-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
								<section>
									<header class="main">
										<h1>{{ book.title }}</h1>
									</header>
									<img src="{{book.image.url}}">
									<h3>Author: {{ book.author }}</h3>
									<p>Posted: {{ book.publish_date }}</p>
                                    <p>Category: {{ book.category }}</p>
									<p>{{book.description}}</p>
									<hr class="major" />
									{% if request.user.is_superuser %}
									<a href="{% url 'update-book' book.id %}" >Update</a>
									<a href="{% url 'delete-book' book.id %}" >Delete</a>
									{% endif %}
								</section>
{% endblock %}

templates/bookinstance_list_borrowed_all.html
{% extends "base.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>

<h3>Status :</h3>
<h4>'d'- Maintenance,</h4>
<h4>'o' - On loan,</h4>
<h4>'a' - Available,</h4>
<h4>'r' - Reserved,</h4>


    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})- status: {{bookinst.status}} - student: {{ bookinst.borrower }}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

templates/delete-book.html
{% extends 'base.html' %}
{% block content %}
<h1>Are you sure want to delete this book?</h1>
<form method="post">
    {% csrf_token %}


     <input class="btn btn-primary" type="submit" value="Yes">
    <a class="btn" href="{% url 'home' %}" role="button">Cancel</a>
</form>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
							<!-- Content -->
								<section>
									<header class="main">
										<h1>Welcome to Books World!</h1>
									</header>
									{% if messages %}
                               <ul class="messages">
                               {% for message in messages %}
                                <div class="alert alert-success" role="alert">{{ message }}</div>
                             {% endfor %}
                               </ul>
                                 {% endif %}




									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel sed vehicula.</p>

									<hr class="major" />

									<div class="posts">
										{% for book in page_obj %}
										<article>
											<a href="#" class="image"><img src="{{ book.image.url }}"  style="width: 200px; height: 200px;" alt="" /></a>
											<h3>{{ book.title }}</h3>
											<p>{{ book.description| truncatewords:15 }}</p>
											<ul class="actions">


												<li><a href="{% url 'detail' book.id %}" class="button">More</a></li>

											</ul>
										</article>
										{% endfor %}
									</div>
								</section>
								<nav aria-label="...">
								  <ul class="pagination pagination-sm">
									  {% if page_obj.has_previous %}
									  <li class="page-item"><a class="page-link" href="{% url 'home'%}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
									  {% endif %}
									<li class="page-item active" aria-current="page">
									  <span class="page-link">{{ page_obj.number}}</span>
									</li>
									{% if page_obj.has_next %}
									<li class="page-item"><a class="page-link" href="{% url 'home'%}?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a></li>
								  	{% endif %}
								  </ul>
								</nav>

							{% endblock%}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Search results:</h1>
<div class="posts">
										{% for book in books %}
										<article>
											<a href="#" class="image"><img src="{{ book.image.url }}"  style="width: 200px; height: 200px;" alt="" /></a>
											<h3>{{ book.title }}</h3>
											<p>{{ book.description| truncatewords:15 }}</p>
											<ul class="actions">


												<li><a href="{% url 'detail' book.id %}" class="button">More</a></li>

											</ul>
										</article>
										{% endfor %}
									</div>
{% endblock %}

templates/update-book.html
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ book_form.as_p }}
     <input class="btn btn-primary" type="submit" value="Submit">
</form>

{% endblock %}